### ISSUE TITLE
Migrating to WDC 3.0

### ISSUE THREAD

**Issue by KryeKuzhinieri** [KeshiaRose/JSON-XML-WDC#7]
Hi, 

It appears that WDC 2.0 is being deprecated. I was wondering if there is a way to migrate this project to version 3.0. Here is the official documentation on the matter: 

```
Important: Tableau Web Data Connector 2.0 (this version) is being deprecated at Tableau 2023.1 and eventually retired. 
We will still support WDC 2.0 until its last compatible version of Tableau (Tableau 2022.4) goes End of Life and is no longer supported.

For information about Tableau Web Data Connector 3.0, 
see the [WDC 3.0 documentation](https://help.tableau.com/current/api/webdataconnector/en-us/index.html).
```

**Comment by KeshiaRose** [comment]
Hi @KryeKuzhinieri, Yes I believe it can be. I'll take a look and see what it would take to do so and let you know!

**Comment by KryeKuzhinieri** [comment]
> Hi @KryeKuzhinieri, Yes I believe it can be. I'll take a look and see what it would take to do so and let you know!

Thanks, much appreciated!

**Comment by KeshiaRose** [comment]
Hi @KryeKuzhinieri, so I spent some time trying to brush up on the new WDC 3.0 SDK and unfortunately it seems like it is waaaaaay more complicated than WDC 2.0. No longer will a simple web app do, the tooling is way more complex and you now need to package the connectors into a file and install them locally on your machine in order to use them. (How do they expect folks to get updates??) Additionally, to create them and have them be able to be used by others you need to get them signed by a trusted certificate authority. 🙄 On top of that, it is no longer possible to use Tableau Public to work on or use WDCs, which I have been using since leaving Tableau. All of these things combined unfortunately means I will not be able to migrate the code to WDC 3.0. The code is openly available and under MIT license so feel free to grab it and see if you can get it to work with 3.0. Hopefully, you can find an alternative solution. I'm sad that Tableau has chosen to go this direction, I think it will make it harder not easier for many folks who simply need to access data on the web. Sorry this is the response, I hope you can understand. 🙁
